/** Major commercial & state-owned banks in Bangladesh (alphabetical). */
export const BANGLADESH_BANKS = [
  'AB Bank',
  'Agrani Bank',
  'Al-Arafah Islami Bank',
  'Bangladesh Commerce Bank',
  'Bangladesh Development Bank (BDBL)',
  'Bangladesh Krishi Bank',
  'Bank Asia',
  'BRAC Bank',
  'Citizens Bank',
  'City Bank',
  'Community Bank Bangladesh',
  'Dhaka Bank',
  'Dutch-Bangla Bank',
  'Eastern Bank',
  'EXIM Bank',
  'First Security Islami Bank',
  'Global Islami Bank',
  'ICB Islamic Bank',
  'IFIC Bank',
  'Islami Bank Bangladesh',
  'Jamuna Bank',
  'Janata Bank',
  'Mercantile Bank',
  'Midland Bank',
  'Modhumoti Bank',
  'Mutual Trust Bank',
  'National Bank',
  'National Credit & Commerce Bank (NCC)',
  'NRB Bank',
  'NRBC Bank',
  'One Bank',
  'Padma Bank',
  'Premier Bank',
  'Prime Bank',
  'Pubali Bank',
  'Rajshahi Krishi Unnayan Bank',
  'Rupali Bank',
  'SBAC Bank',
  'Shahjalal Islami Bank',
  'Shimanto Bank',
  'Social Islami Bank',
  'Sonali Bank',
  'Southeast Bank',
  'Standard Bank',
  'Standard Chartered Bank',
  'The Premier Bank',
  'Trust Bank',
  'Union Bank',
  'Uttara Bank',
  'Woori Bank',
] as const

export type BangladeshBank = (typeof BANGLADESH_BANKS)[number]
