import { format } from 'date-fns'
import { jsPDF } from 'jspdf'
import ExcelJS from 'exceljs'
import { HOTEL_NAME } from './reservation-terms'
import { getLogoDataUrl } from './reservation-document-html'

export type CleaningStaffListRecord = {
  id: string
  staffCode: string
  name: string
  phone?: string | null
  active?: boolean
  taskCounts: {
    total: number
    pending: number
    inProgress: number
    completed: number
  }
}

export type CleaningStaffWorkHistoryRecord = {
  staffCode: string
  staffName: string
  roomNumber: string
  floor: number
  taskType: string
  status: string
  workAt: string
  startedAt?: string | null
  completedAt?: string | null
  notes?: string | null
}

export type CleaningStaffExportMeta = {
  exportedAt?: Date
  generatedBy?: { name: string; email?: string }
  staffFilter?: string
}

function formatGeneratedBy(user?: CleaningStaffExportMeta['generatedBy']): string {
  if (!user?.name) return '—'
  if (user.email) return `${user.name} (${user.email})`
  return user.name
}

function formatTaskType(value: string): string {
  return value.replace(/_/g, ' ')
}

function formatStatus(value: string): string {
  return value.replace(/_/g, ' ')
}

async function loadExportLogo(): Promise<{ dataUrl: string; base64: string } | null> {
  try {
    const dataUrl = await getLogoDataUrl()
    const base64 = dataUrl.includes(',') ? dataUrl.split(',')[1]! : dataUrl
    return { dataUrl, base64 }
  } catch {
    return null
  }
}

function triggerBrowserDownload(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = fileName
  anchor.click()
  URL.revokeObjectURL(url)
}

export function cleaningStaffListFileName(ext: 'xlsx' | 'pdf'): string {
  return `cleaning-staff-list-${format(new Date(), 'yyyy-MM-dd-HHmm')}.${ext}`
}

export function cleaningStaffHistoryFileName(ext: 'xlsx' | 'pdf', staffCode?: string): string {
  const safe = staffCode ? staffCode.replace(/[^\w-]+/g, '-') : 'all'
  return `cleaning-staff-history-${safe}-${format(new Date(), 'yyyy-MM-dd-HHmm')}.${ext}`
}

function staffListRows(staff: CleaningStaffListRecord[]) {
  return staff.map((s) => ({
    'Staff ID': s.staffCode,
    Name: s.name,
    Phone: s.phone ?? '',
    Status: s.active === false ? 'Inactive' : 'Active',
    'Total Tasks': s.taskCounts.total,
    Completed: s.taskCounts.completed,
    'In Progress': s.taskCounts.inProgress,
    Pending: s.taskCounts.pending,
  }))
}

function historyRows(history: CleaningStaffWorkHistoryRecord[]) {
  return history.map((h) => {
    const workDate = new Date(h.workAt)
    return {
      'Staff ID': h.staffCode,
      'Staff Name': h.staffName,
      Date: format(workDate, 'dd MMM yyyy'),
      Time: format(workDate, 'HH:mm'),
      'Room No': h.roomNumber,
      Floor: h.floor,
      'Task Type': formatTaskType(h.taskType),
      Status: formatStatus(h.status),
      Started: h.startedAt ? format(new Date(h.startedAt), 'dd MMM yyyy HH:mm') : '',
      Completed: h.completedAt ? format(new Date(h.completedAt), 'dd MMM yyyy HH:mm') : '',
      Notes: h.notes ?? '',
    }
  })
}

async function writeExcelReport(
  title: string,
  headers: string[],
  rows: Record<string, string | number>[],
  meta: CleaningStaffExportMeta,
  fileName: string
) {
  const workbook = new ExcelJS.Workbook()
  const sheet = workbook.addWorksheet('Report')
  const exportedAt = meta.exportedAt ?? new Date()
  let row = 1

  sheet.mergeCells(row, 1, row, Math.max(headers.length, 3))
  sheet.getCell(row, 1).value = HOTEL_NAME
  sheet.getCell(row, 1).font = { bold: true, size: 16 }
  row += 1
  sheet.mergeCells(row, 1, row, Math.max(headers.length, 3))
  sheet.getCell(row, 1).value = title
  sheet.getCell(row, 1).font = { bold: true, size: 12 }
  row += 2

  const info: [string, string][] = [
    ['Exported', format(exportedAt, 'dd MMM yyyy, HH:mm')],
    ['Generated by', formatGeneratedBy(meta.generatedBy)],
  ]
  if (meta.staffFilter) info.push(['Staff filter', meta.staffFilter])

  for (const [label, value] of info) {
    sheet.getCell(row, 1).value = label
    sheet.getCell(row, 1).font = { bold: true }
    sheet.getCell(row, 2).value = value
    row += 1
  }
  row += 1

  headers.forEach((header, index) => {
    const cell = sheet.getCell(row, index + 1)
    cell.value = header
    cell.font = { bold: true }
  })
  row += 1

  for (const dataRow of rows) {
    headers.forEach((header, index) => {
      sheet.getCell(row, index + 1).value = dataRow[header] ?? ''
    })
    row += 1
  }

  const buffer = await workbook.xlsx.writeBuffer()
  triggerBrowserDownload(
    new Blob([buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    }),
    fileName
  )
}

async function writePdfReport(
  title: string,
  columns: Array<{ header: string; width: number; value: (row: Record<string, string | number>) => string }>,
  rows: Record<string, string | number>[],
  meta: CleaningStaffExportMeta,
  fileName: string
) {
  const logo = await loadExportLogo()
  const pdf = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape', compress: true })
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const marginX = 10
  const marginBottom = 10
  let y = 10

  if (logo) {
    pdf.addImage(logo.dataUrl, 'PNG', marginX, y, 12, 12)
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(14)
    pdf.text(HOTEL_NAME, marginX + 16, y + 5)
    pdf.setFontSize(11)
    pdf.text(title, marginX + 16, y + 10)
    y += 16
  } else {
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(14)
    pdf.text(HOTEL_NAME, marginX, y + 4)
    pdf.setFontSize(11)
    pdf.text(title, marginX, y + 10)
    y += 14
  }

  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(8)
  const exportedAt = meta.exportedAt ?? new Date()
  pdf.text(`Exported: ${format(exportedAt, 'dd MMM yyyy, HH:mm')}`, marginX, y)
  y += 4
  pdf.text(`Generated by: ${formatGeneratedBy(meta.generatedBy)}`, marginX, y)
  y += 4
  if (meta.staffFilter) {
    pdf.text(`Staff filter: ${meta.staffFilter}`, marginX, y)
    y += 4
  }
  pdf.text(`Total records: ${rows.length}`, marginX, y)
  y += 6

  const lineHeight = 3.6
  const cellPad = 1.5

  const drawHeader = () => {
    pdf.setFillColor(245, 245, 245)
    pdf.rect(marginX, y - 4, columns.reduce((s, c) => s + c.width, 0), 6, 'F')
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(7)
    let x = marginX + cellPad
    for (const col of columns) {
      pdf.text(col.header, x, y)
      x += col.width
    }
    y += 6
    pdf.setFont('helvetica', 'normal')
  }

  drawHeader()

  for (const row of rows) {
    const lines = columns.map((col) =>
      pdf.splitTextToSize(col.value(row), Math.max(col.width - cellPad * 2, 8))
    )
    const maxLines = Math.max(...lines.map((l) => l.length), 1)
    const rowHeight = maxLines * lineHeight + 1.5

    if (y + rowHeight > pageHeight - marginBottom) {
      pdf.addPage()
      y = marginX
      drawHeader()
    }

    let x = marginX + cellPad
    for (let i = 0; i < columns.length; i++) {
      pdf.text(lines[i], x, y)
      x += columns[i].width
    }
    y += rowHeight
  }

  pdf.save(fileName)
}

export async function downloadCleaningStaffListExcel(
  staff: CleaningStaffListRecord[],
  meta: CleaningStaffExportMeta = {}
) {
  if (!staff.length) throw new Error('No cleaning staff to export')
  const rows = staffListRows(staff)
  const headers = Object.keys(rows[0])
  await writeExcelReport('Cleaning Staff List', headers, rows, meta, cleaningStaffListFileName('xlsx'))
}

export async function downloadCleaningStaffListPdf(
  staff: CleaningStaffListRecord[],
  meta: CleaningStaffExportMeta = {}
) {
  if (!staff.length) throw new Error('No cleaning staff to export')
  const rows = staffListRows(staff)
  const columns = [
    { header: 'Staff ID', width: 22, value: (r) => String(r['Staff ID']) },
    { header: 'Name', width: 35, value: (r) => String(r.Name) },
    { header: 'Phone', width: 28, value: (r) => String(r.Phone) },
    { header: 'Total', width: 14, value: (r) => String(r['Total Tasks']) },
    { header: 'Done', width: 14, value: (r) => String(r.Completed) },
    { header: 'In Prog.', width: 14, value: (r) => String(r['In Progress']) },
    { header: 'Pending', width: 14, value: (r) => String(r.Pending) },
  ]
  await writePdfReport('Cleaning Staff List', columns, rows, meta, cleaningStaffListFileName('pdf'))
}

export async function downloadCleaningStaffHistoryExcel(
  history: CleaningStaffWorkHistoryRecord[],
  meta: CleaningStaffExportMeta = {}
) {
  if (!history.length) throw new Error('No work history to export')
  const rows = historyRows(history)
  const headers = Object.keys(rows[0])
  await writeExcelReport(
    'Cleaning Staff Work History',
    headers,
    rows,
    meta,
    cleaningStaffHistoryFileName('xlsx', meta.staffFilter)
  )
}

export async function downloadCleaningStaffHistoryPdf(
  history: CleaningStaffWorkHistoryRecord[],
  meta: CleaningStaffExportMeta = {}
) {
  if (!history.length) throw new Error('No work history to export')
  const rows = historyRows(history)
  const columns = [
    { header: 'Staff ID', width: 18, value: (r) => String(r['Staff ID']) },
    { header: 'Name', width: 28, value: (r) => String(r['Staff Name']) },
    { header: 'Date', width: 22, value: (r) => String(r.Date) },
    { header: 'Time', width: 14, value: (r) => String(r.Time) },
    { header: 'Room', width: 14, value: (r) => String(r['Room No']) },
    { header: 'Floor', width: 12, value: (r) => String(r.Floor) },
    { header: 'Task', width: 22, value: (r) => String(r['Task Type']) },
    { header: 'Status', width: 20, value: (r) => String(r.Status) },
  ]
  await writePdfReport(
    'Cleaning Staff Work History',
    columns,
    rows,
    meta,
    cleaningStaffHistoryFileName('pdf', meta.staffFilter)
  )
}
