import { format } from 'date-fns'
import { jsPDF } from 'jspdf'
import ExcelJS from 'exceljs'
import { formatGuestId } from './id-type-label'
import {
  formatListBookingCheckIn,
  type BookingListDatetimeFields,
  type HotelTimes,
} from './hotel-times'
import { HOTEL_NAME } from './reservation-terms'
import type { GuestsExportFilterLabels } from './booking-date-filter'
import { getLogoDataUrl } from './reservation-document-html'

export type GuestExportRecord = {
  name: string
  email?: string | null
  phone: string
  address?: string | null
  idType?: string | null
  idNumber?: string | null
  nationality?: string | null
  stay?: (BookingListDatetimeFields & { roomNumber?: string | null }) | null
}

export type GuestsExportMeta = {
  filters?: GuestsExportFilterLabels
  exportedAt?: Date
  generatedBy?: {
    name: string
    email?: string
    role?: string
  }
}

function resolveExportFilters(meta: GuestsExportMeta): GuestsExportFilterLabels {
  if (meta.filters) return meta.filters
  return { date: 'All dates', search: '—', reportTitle: 'Guest List Report' }
}

function formatGeneratedBy(user?: GuestsExportMeta['generatedBy']): string {
  if (!user?.name) return '—'
  if (user.email) return `${user.name} (${user.email})`
  return user.name
}

export function mapGuestToExportRow(
  guest: GuestExportRecord,
  times: HotelTimes
): Record<string, string> {
  return {
    'Guest name': guest.name,
    Email: guest.email ?? '',
    Mobile: guest.phone,
    'NID / Passport / License': formatGuestId(guest.idType, guest.idNumber),
    Address: guest.address ?? '',
    Nationality: guest.nationality ?? '',
    Room: guest.stay?.roomNumber ?? '',
    'Check-in': guest.stay ? formatListBookingCheckIn(guest.stay, times) : '',
  }
}

export function guestsExportFileName(ext: 'xlsx' | 'pdf'): string {
  const stamp = format(new Date(), 'yyyy-MM-dd-HHmm')
  return `guests-${stamp}.${ext}`
}

async function loadExportLogo(): Promise<{ dataUrl: string; base64: string } | null> {
  try {
    const dataUrl = await getLogoDataUrl()
    const base64 = dataUrl.includes(',') ? dataUrl.split(',')[1]! : dataUrl
    return { dataUrl, base64 }
  } catch {
    return null
  }
}

function triggerBrowserDownload(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = fileName
  anchor.click()
  URL.revokeObjectURL(url)
}

export async function downloadGuestsExcel(
  guests: GuestExportRecord[],
  times: HotelTimes,
  meta: GuestsExportMeta = {}
): Promise<void> {
  if (!guests.length) {
    throw new Error('No guests to export')
  }
  const rows = guests.map((g) => mapGuestToExportRow(g, times))
  const headers = Object.keys(rows[0])
  const exportedAt = meta.exportedAt ?? new Date()
  const filters = resolveExportFilters(meta)
  const colCount = headers.length
  const logo = await loadExportLogo()

  const workbook = new ExcelJS.Workbook()
  const sheet = workbook.addWorksheet('Guests')
  let row = 1

  const reportTitle = filters.reportTitle

  sheet.getRow(1).height = 22
  sheet.getRow(2).height = 18

  const logoColSpan = 1.6
  const textColSpan = 5.5
  const headerBlockCols = logo ? logoColSpan + textColSpan : colCount
  const headerStartCol0 = logo ? Math.max(0, (colCount - headerBlockCols) / 2) : 0
  const textStartCol = logo ? Math.floor(headerStartCol0 + logoColSpan) + 1 : 1
  const textEndCol = logo
    ? Math.min(colCount, Math.max(textStartCol, Math.ceil(headerStartCol0 + logoColSpan + textColSpan)))
    : colCount

  if (logo) {
    const imageId = workbook.addImage({ base64: logo.base64, extension: 'png' })
    sheet.addImage(imageId, {
      tl: { col: headerStartCol0 + 0.05, row: 0.08 },
      ext: { width: 44, height: 44 },
    })
  }

  if (textEndCol >= textStartCol) {
    sheet.mergeCells(1, textStartCol, 1, textEndCol)
    sheet.mergeCells(2, textStartCol, 2, textEndCol)
  }

  const hotelCell = sheet.getCell(1, textStartCol)
  hotelCell.value = HOTEL_NAME
  hotelCell.font = { bold: true, size: 16 }
  hotelCell.alignment = { horizontal: logo ? 'left' : 'center', vertical: 'middle' }

  const titleCell = sheet.getCell(2, textStartCol)
  titleCell.value = reportTitle
  titleCell.font = { bold: true, size: 12 }
  titleCell.alignment = { horizontal: logo ? 'left' : 'center', vertical: 'middle' }

  row = 3

  const infoRows: [string, string | number][] = [
    ['Generated by', formatGeneratedBy(meta.generatedBy)],
    ['Exported', format(exportedAt, 'dd MMM yyyy, HH:mm')],
    ['Date', filters.date],
    ['Search', filters.search],
    ['Total records', guests.length],
  ]
  for (const [label, value] of infoRows) {
    sheet.getCell(row, 1).value = label
    sheet.getCell(row, 1).font = { bold: true }
    sheet.getCell(row, 2).value = value
    row += 1
  }

  row += 1
  headers.forEach((header, index) => {
    const cell = sheet.getCell(row, index + 1)
    cell.value = header
    cell.font = { bold: true }
  })
  row += 1

  for (const dataRow of rows) {
    headers.forEach((header, index) => {
      sheet.getCell(row, index + 1).value = dataRow[header] ?? ''
    })
    row += 1
  }

  headers.forEach((_, index) => {
    sheet.getColumn(index + 1).width = Math.max(14, headers[index]?.length ?? 10)
  })

  const buffer = await workbook.xlsx.writeBuffer()
  triggerBrowserDownload(
    new Blob([buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    }),
    guestsExportFileName('xlsx')
  )
}

type PdfColumn = {
  header: string
  width: number
  value: (guest: GuestExportRecord, times: HotelTimes) => string
}

const PDF_COLUMNS: PdfColumn[] = [
  { header: 'Guest name', width: 36, value: (g) => g.name },
  { header: 'Email', width: 38, value: (g) => g.email ?? '—' },
  { header: 'Mobile', width: 28, value: (g) => g.phone },
  {
    header: 'ID',
    width: 32,
    value: (g) => formatGuestId(g.idType, g.idNumber),
  },
  { header: 'Address', width: 40, value: (g) => g.address ?? '—' },
  { header: 'Nationality', width: 24, value: (g) => g.nationality ?? '—' },
  { header: 'Room', width: 16, value: (g) => g.stay?.roomNumber ?? '—' },
  {
    header: 'Check-in',
    width: 34,
    value: (g, t) => (g.stay ? formatListBookingCheckIn(g.stay, t) : '—'),
  },
]

const PDF_LINE_HEIGHT = 3.6
const PDF_CELL_PAD = 1.5

function splitCellLines(pdf: jsPDF, text: string, colWidth: number): string[] {
  const content = (text || '—').trim() || '—'
  return pdf.splitTextToSize(content, Math.max(colWidth - PDF_CELL_PAD * 2, 8))
}

function scalePdfColumns(columns: PdfColumn[], targetWidth: number): PdfColumn[] {
  const baseTotal = columns.reduce((sum, col) => sum + col.width, 0)
  if (baseTotal <= 0) return columns
  const scale = targetWidth / baseTotal
  return columns.map((col) => ({ ...col, width: col.width * scale }))
}

export async function downloadGuestsPdf(
  guests: GuestExportRecord[],
  times: HotelTimes,
  meta: GuestsExportMeta = {}
): Promise<void> {
  if (!guests.length) {
    throw new Error('No guests to export')
  }

  const logo = await loadExportLogo()
  const pdf = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape', compress: true })
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const marginX = 10
  const marginTop = 10
  const marginBottom = 10
  const headerRowHeight = 7
  let y = marginTop

  const exportedAt = meta.exportedAt ?? new Date()
  const filters = resolveExportFilters(meta)
  const reportTitle = filters.reportTitle
  const logoSize = 12
  const headerY = marginTop
  const headerGap = 4

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(16)
  const nameWidth = pdf.getTextWidth(HOTEL_NAME)
  pdf.setFontSize(12)
  const subtitleWidth = pdf.getTextWidth(reportTitle)
  const textWidth = Math.max(nameWidth, subtitleWidth)
  const blockWidth = (logo ? logoSize + headerGap : 0) + textWidth
  const blockStartX = (pageWidth - blockWidth) / 2

  if (logo) {
    pdf.addImage(logo.dataUrl, 'PNG', blockStartX, headerY, logoSize, logoSize)
  }

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(16)
  if (logo) {
    pdf.text(HOTEL_NAME, blockStartX + logoSize + headerGap, headerY + 5)
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(12)
    pdf.text(reportTitle, blockStartX + logoSize + headerGap, headerY + 10)
  } else {
    pdf.text(HOTEL_NAME, pageWidth / 2, headerY + 7, { align: 'center' })
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(12)
    pdf.text(reportTitle, pageWidth / 2, headerY + 14, { align: 'center' })
  }

  y = headerY + logoSize + 6

  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(8)
  const metaLines = [
    `Generated by: ${formatGeneratedBy(meta.generatedBy)}`,
    `Exported: ${format(exportedAt, 'dd MMM yyyy, HH:mm')}`,
    `Date: ${filters.date}`,
    `Search: ${filters.search}`,
    `Total records: ${guests.length}`,
  ]
  for (const line of metaLines) {
    pdf.text(line, marginX, y)
    y += 4
  }
  y += 2

  const tableWidth = pageWidth - marginX * 2
  const pdfColumns = scalePdfColumns(PDF_COLUMNS, tableWidth)

  const drawHeader = () => {
    pdf.setFillColor(240, 240, 240)
    pdf.rect(marginX, y - 4, tableWidth, headerRowHeight, 'F')
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(7)
    let x = marginX + PDF_CELL_PAD
    for (const col of pdfColumns) {
      pdf.text(col.header, x, y)
      x += col.width
    }
    y += headerRowHeight
    pdf.setFont('helvetica', 'normal')
  }

  drawHeader()

  for (const guest of guests) {
    const cellLines = pdfColumns.map((col) =>
      splitCellLines(pdf, col.value(guest, times), col.width)
    )
    const rowHeight = Math.max(...cellLines.map((lines) => lines.length * PDF_LINE_HEIGHT)) + 2

    if (y + rowHeight > pageHeight - marginBottom) {
      pdf.addPage()
      y = marginTop
      drawHeader()
    }

    let x = marginX + PDF_CELL_PAD
    for (let i = 0; i < pdfColumns.length; i++) {
      const lines = cellLines[i]
      let lineY = y
      for (const line of lines) {
        pdf.text(line, x, lineY)
        lineY += PDF_LINE_HEIGHT
      }
      x += pdfColumns[i].width
    }
    y += rowHeight
  }

  pdf.save(guestsExportFileName('pdf'))
}

export function buildGuestsExportQuery(
  filters: {
    search?: string
    dateFrom?: string
    dateTo?: string
  },
  limit = 5000
): string {
  const params = new URLSearchParams()
  params.set('page', '1')
  params.set('limit', String(limit))
  if (filters.search) params.set('search', filters.search)
  if (filters.dateFrom) params.set('dateFrom', filters.dateFrom)
  if (filters.dateTo) params.set('dateTo', filters.dateTo)
  return `/customers?${params.toString()}`
}
